# Generated by Django 2.1.4 on 2019-01-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0002_auto_20190118_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='SAge',
        ),
        migrations.AddField(
            model_name='student',
            name='Lname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
