# Generated by Django 2.1.4 on 2019-01-18 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0003_auto_20190118_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='FName',
            new_name='SFName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Lname',
            new_name='SLname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='SAddress',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='SClass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='SEmail',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='SID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
