# Generated by Django 2.1.4 on 2019-02-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher_App', '0005_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tmid', models.IntegerField()),
                ('room_no', models.IntegerField()),
                ('time', models.TimeField()),
                ('day', models.CharField(max_length=20)),
                ('Tid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher_App.Teacher')),
            ],
        ),
    ]
