# Generated by Django 2.1.4 on 2019-02-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0004_auto_20190118_2250'),
        ('Teacher_App', '0005_assignments'),
        ('Principal_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('PFname', models.CharField(max_length=20)),
                ('PLname', models.CharField(max_length=20)),
                ('Pemail', models.EmailField(max_length=254)),
                ('Pgender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('PSId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_App.Student')),
                ('PTid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher_App.Teacher')),
            ],
        ),
    ]
