# Generated by Django 2.1.4 on 2019-01-18 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('TFName', models.CharField(max_length=30)),
                ('TLname', models.CharField(blank=True, max_length=30)),
                ('TCity', models.CharField(blank=True, max_length=20)),
                ('TEmail', models.EmailField(blank=True, max_length=30)),
                ('TClass', models.IntegerField(blank=True)),
                ('TSubject', models.CharField(max_length=20)),
            ],
        ),
    ]
