# Generated by Django 2.1.4 on 2019-01-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0004_auto_20190118_2250'),
        ('Teacher_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='TSId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_App.Student'),
        ),
    ]
