# Generated by Django 2.1.4 on 2019-02-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_App', '0003_attendance_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Roll_no',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
