# Generated by Django 2.1.4 on 2019-02-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_App', '0004_auto_20190118_2250'),
        ('Teacher_App', '0004_auto_20190204_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.IntegerField()),
                ('assingment', models.CharField(max_length=30)),
                ('deadline', models.DateField()),
                ('submit_status', models.BooleanField()),
                ('Roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_App.Student')),
            ],
        ),
    ]
